### ISSUE TITLE
gx4 build error on indigo

### ISSUE THREAD

**Issue by droter** [KumarRobotics/imu_3dm_gx4#11] opened 2015-06-30 16:13 UTC
Hi,

I am getting this error when running catkin_make when installing the imu_3dm_gx4.

/home/viki/catkin_ws/src/imu_3dm_gx4/src/imu.cpp:243:18: error: unused variable ‘sz’ [-Werror=unused-variable]
cc1plus: all warnings being treated as errors
make[2]: *** [imu_3dm_gx4/CMakeFiles/imu_3dm_gx4.dir/src/imu.cpp.o] Error 1
make[1]: *** [imu_3dm_gx4/CMakeFiles/imu_3dm_gx4.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

I checked this page for additional installs:
http://kumar-robotics-github-documentation.readthedocs.org/en/latest/references/env_setup.html

I am running Trusty 14.04 LTS and indigo.

Is this error related to c++11?

Thanks,

Matt

**Comment by versatran01** [comment] 2015-06-30 16:15
Quick fix is to remove the -Werror in the add_defitions.

**Comment by droter** [comment] 2015-06-30 17:20
Yes, that worked.  It is able to build now.

When I try to connect I get:
process[imu-2]: started with pid [4534]
[ INFO] [1435684232.475073629]: Selecting baud rate 115200
[ERROR] [1435684233.205271645]: Exception: Device did not respond to ping.
Timed-out while reading. Time-out limit is 300ms.

[imu-2] process has finished cleanly

Is there a way to increase the Time-out or is this a different problem?

Matt

**Comment by versatran01** [comment] 2015-06-30 17:25
Are you able to see the device via the `lsusb` command?
Do you have the correct access permission to the device?

**Comment by droter** [comment] 2015-06-30 17:46
This is the output of lsusb:
Bus 002 Device 007: ID 0483:5740 STMicroelectronics STM32F407

I have added the user to the dialout group:
viki@c3po:~/catkin_ws/src/imu_3dm_gx4/src$ groups viki
viki : viki adm dialout cdrom sudo dip plugdev lpadmin sambashare

viki@c3po:~/catkin_ws/src/imu_3dm_gx4/src$ ls -al /dev/ttyACM0
crwxrwxrwx 1 root dialout 166, 0 Jun 30 12:42 /dev/ttyACM0

**Comment by mwatterson** [comment] 2015-06-30 17:48
@droter  I've encountered your second problem often.  It is fixed by unplugging and replugging the imu.  We've tried to find a software fix, but haven't been able to.

**Comment by droter** [comment] 2015-06-30 17:52
setting /run_id to a6da3fa2-1f50-11e5-a3d8-080027b46cdd
process[rosout-1]: started with pid [7009]
started core service [/rosout]
process[imu-2]: started with pid [7026]
[ INFO] [1435686696.801696619]: Selecting baud rate 115200
[ INFO] [1435686697.526912588]: Fetching device info.
[ INFO] [1435686697.562773266]: 	Device options: 5g,300dps
[ INFO] [1435686697.562966145]: 	Firmware version: 1104
[ INFO] [1435686697.563208181]: 	Model name: 3DM-GX4-25
[ INFO] [1435686697.563272971]: 	Model number: 6234-4220
[ INFO] [1435686697.563311157]: 	Serial number: 6234.42680
[ INFO] [1435686697.563347428]: Idling the device
[ERROR] [1435686697.865542375]: Timeout: Timed-out while reading. Time-out limit is 300ms.

Made it further.  Is there a way to increase the Time-out?

**Comment by versatran01** [comment] 2015-06-30 18:31
try modifying 
#define kDefaultTimeout    (300)
in src/imu.cpp

**Comment by gareth-cross** [comment] 2015-06-30 18:40
If this issue is the same as the one experience by @mwatterson, it is not a result of the timeout option. The problem occurs when the IMU does not return the second byte of the checksum on the last idle command. This problem was referenced (but not yet resolved) in #7. 

It is unlikely that the issue is with the IMU itself, but I am uncertain where the problem occurs. I have observed that when the C `read` function obtains the last few bytes of the packet, the first byte of the checksum will be present - but the second is simply the header of the next packet. It seems the problem occurs before the data arrives at the driver.

**Comment by droter** [comment] 2015-06-30 19:27
I am able to get IMU data now.  It looks like it is updating every 15 seconds.
---
header: 
  seq: 22866
  stamp: 
    secs: 1435692326
    nsecs: 44597743
  frame_id: imu
orientation: 
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.00604161946103
  y: 0.00419787084684
  z: 0.00311058945954
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 0.983809230923
  y: 1.23034244381
  z: -9.66719827469
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 22867
  stamp: 
    secs: 1435692341
    nsecs: 45368222
  frame_id: imu
orientation: 
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.00615513138473
  y: 0.0042565301992
  z: 0.00381498131901
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 1.03700269565
  y: 1.19358631915
  z: -9.63896119124
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---

**Comment by gareth-cross** [comment] 2015-06-30 22:07
Do you mean the data is arriving at (1/15) Hz, or the values are only updating every 15 seconds and the publishing is happening at a faster rate?

**Comment by droter** [comment] 2015-06-30 22:21
I am using rostopic echo /imu/imu

The launch file is set to 100hz but I don't know if the rostopic is publishing everything that is coming in.

**Closed** 2015-07-01 23:19 UTC
